# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=50)),
                ('archived', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=25)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_thread',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.AddField(
            model_name='watchedcomment',
            name='parent_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditpoller.WatchedThread'),
        ),
    ]
