# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0003_auto_20170228_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedthread',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
