# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0004_auto_20170228_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedthread',
            name='self',
            field=models.BooleanField(default=True),
        ),
    ]
