# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0005_watchedthread_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedthread',
            name='self',
        ),
        migrations.AddField(
            model_name='watchedthread',
            name='self_post',
            field=models.BooleanField(default=False),
        ),
    ]
