# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0007_watchedthread_self_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedcomment',
            name='comment_author',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
