# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0008_watchedcomment_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedcomment',
            name='comment_author',
            field=models.CharField(max_length=100),
        ),
    ]
