# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0009_auto_20170301_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedcomment',
            name='comment_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
