# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0010_auto_20170301_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedcomment',
            name='text',
            field=models.CharField(max_length=50000),
        ),
    ]
