# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0011_auto_20170302_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedcomment',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
