# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0014_auto_20170304_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchedSubredditThreads',
            new_name='WatchedSubredditThread',
        ),
    ]
