# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redditpoller', '0015_auto_20170304_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedsubreddit',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
