# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0016_watchedsubreddit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedsubreddit',
            name='username',
        ),
    ]
