# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0018_auto_20170307_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedsubreddit',
            old_name='checked_date',
            new_name='submitted_date',
        ),
        migrations.RenameField(
            model_name='watchedthread',
            old_name='date',
            new_name='thread_date',
        ),
    ]
