# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0019_auto_20170311_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedthread',
            name='last_checked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='watchedthread',
            name='watch_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
