# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redditpoller', '0021_auto_20170312_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_username', models.CharField(max_length=30)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('watch_interval', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedUserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditpoller.WatchedUser')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedUserThreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('thread_date', models.CharField(max_length=50)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditpoller.WatchedUser')),
            ],
        ),
    ]
