# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0022_watcheduser_watchedusercomments_watcheduserthreads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchedUserComments',
            new_name='WatchedUserComment',
        ),
        migrations.RenameModel(
            old_name='WatchedUserThreads',
            new_name='WatchedUserThread',
        ),
    ]
