# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0023_auto_20170314_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedsubredditthread',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchedsubredditthread',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
