# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditpoller', '0024_auto_20170318_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedcomment',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchedthread',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchedthread',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchedusercomment',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watcheduserthread',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watcheduserthread',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
